{% set name = "ChessAnalysisPipeline" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ChessAnalysisPipeline-{{ version }}.tar.gz
  sha256: d99c8163a2ba173ccd8ef6310a6d9236d589b51fbc280361e98f8009632bed14

build:
  entry_points:
    - CHAP = CHAP.runner:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pyyaml

test:
  imports:
    - CHAP
    - MLaaS
  commands:
    - pip check
    - CHAP --help
  requires:
    - pip

about:
  home: https://github.com/CHESSComputing/ChessAnalysisPipeline
  summary: CHESS analysis pipeline framework
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/CHESSComputing/ChessAnalysisPipeline

extra:
  recipe-maintainers:
    - keara-soloway
    - rolfverberg
