{% set name = "ChessAnalysisPipeline" %}
{% set version = "2026.2.25" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/08/58/43dedbddabef42578e12abadc95ad2fd41bc02beeebf745a178b74917ae1/chessanalysispipeline-{{ version }}.tar.gz
  sha256: 113a3b8b8af3a22bccc87f522d49568697d52f503c8555db27ecc82c69f9fd45

build:
  entry_points:
    - CHAP = CHAP.runner:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pydantic
    - pyyaml

test:
  imports:
    - CHAP
  commands:
    - pip check
    - CHAP --help
  requires:
    - python {{ python_min }}
    - pip
    - numpy
    - pydantic
    - pyyaml

about:
  home: https://github.com/CHESSComputing/ChessAnalysisPipeline
  summary: CHESS analysis pipeline framework
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/CHESSComputing/ChessAnalysisPipeline

extra:
  recipe-maintainers:
    - keara-soloway
    - rolfverberg
