{% set name = "ChessAnalysisPipeline" %}
{% set version = "1.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ChessAnalysisPipeline-{{ version }}.tar.gz
  sha256: 9e00ab59380798baad405f7e15e9f06bfd2386c7b0ea6344fea0adfee19cee79

build:
  entry_points:
    - CHAP = CHAP.runner:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - CHAP
    - MLaaS
  commands:
    - pip check
    - CHAP --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/CHESSComputing/ChessAnalysisPipeline
  summary: CHESS analysis pipeline framework
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/CHESSComputing/ChessAnalysisPipeline

extra:
  recipe-maintainers:
    - keara-soloway
    - rolfverberg
