{% set name = "ChessAnalysisPipeline" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ChessAnalysisPipeline-{{ version }}.tar.gz
  sha256: 1438747312a3ea0dc5b70dba570a22c8ea16ea8ce06b1be194101da12f80130d

build:
  entry_points:
    - CHAP = CHAP.runner:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pyyaml

test:
  imports:
    - CHAP
    - MLaaS
  commands:
    - pip check
    - CHAP --help
  requires:
    - pip

about:
  home: https://github.com/CHESSComputing/ChessAnalysisPipeline
  summary: CHESS analysis pipeline framework
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/CHESSComputing/ChessAnalysisPipeline

extra:
  recipe-maintainers:
    - keara-soloway
    - rolfverberg
