{% set name = "ChessAnalysisPipeline" %}
{% set version = "2026.4.24" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/1e/94/274001b3156b9dcf01bce7434149ad2ef18cb3fe01fe67d5fbc644a2a4c9/chessanalysispipeline-{{ version }}.tar.gz
  sha256: cd8e443879cb515d08c6be6dd95f9ccc57c1d244a036654a412f5509c93ef0b3

build:
  entry_points:
    - CHAP = CHAP.runner:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pydantic
    - pyyaml

test:
  imports:
    - CHAP
  commands:
    - pip check
    - CHAP --help
  requires:
    - python {{ python_min }}
    - pip
    - numpy
    - pydantic
    - pyyaml

about:
  home: https://github.com/CHESSComputing/ChessAnalysisPipeline
  summary: CHESS analysis pipeline framework
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/CHESSComputing/ChessAnalysisPipeline

extra:
  recipe-maintainers:
    - keara-soloway
    - rolfverberg
