{% set name = "ChessAnalysisPipeline" %}
{% set version = "2026.7.31" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/6a/74/a91ae834c28cb75411adf93e292774da4563c12b0f0e60b78819c2d95953/chessanalysispipeline-{{ version }}.tar.gz
  sha256: 8b72b941d85be49a5a2840f52a10fcd060706fe5b6106518312be9d6059f868f

build:
  entry_points:
    - CHAP = CHAP.runner:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pydantic
    - pyyaml

test:
  imports:
    - CHAP
  commands:
    - pip check
    - CHAP --help
  requires:
    - python {{ python_min }}
    - pip
    - numpy
    - pydantic
    - pyyaml

about:
  home: https://github.com/CHESSComputing/ChessAnalysisPipeline
  summary: CHESS analysis pipeline framework
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/CHESSComputing/ChessAnalysisPipeline

extra:
  recipe-maintainers:
    - keara-soloway
    - rolfverberg
